### ISSUE TITLE
Misleading regex pattern in the plugin description

### ISSUE THREAD

**Issue by mudrd8mz** [PawelSuwinski/moodle-auth_emailotp#1]
The description at https://moodle.org/plugins/auth_emailotp and the description at _Site administration > Plugins > Authentication > Email OTP_ shows the following as an example field matching pattern:

```
'#/?P<FIRST>[^\.]+)\.(?P<LAST>[^@]+)@(?P<COMPANY>[^\.]+).*#',
```

It does not seem right:

* The trailing `'` and the heading `',` probably should not be there?
* There is a mismatch of brackets reported by the validator

I suppose the intention was to have it like

```
#(?P<FIRST>[^\.]+)\.(?P<LAST>[^@]+)@(?P<COMPANY>[^\.]+).*#
```
or so?

**Comment by PawelSuwinski** [comment]
Thanks, it is mispelling, exactly as you wrote. I will fix next week.
